export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GLOBAL_SUCCESS = "GLOBAL_SUCCESS";
export const GLOBAL_ERROR = "GLOBAL_ERROR";
export const ACTIVATION_REQUIRED = "ACTIVATION_REQUIRED";
export const LIVE_LISTS = "LIVE_LISTS";
export const LIVE_LISTS_INCREMENT = "LIVE_LISTS_INCREMENT";
export const SET_CURRENT_LIVE = "SET_CURRENT_LIVE";
