export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GLOBAL_SUCCESS = "GLOBAL_SUCCESS";
export const GLOBAL_ERROR = "GLOBAL_ERROR";
export const ACTIVATION_REQUIRED = "ACTIVATION_REQUIRED";
